# Generated by Django 3.2 on 2023-05-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
