# Generated by Django 3.2 on 2023-05-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_space_step_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='is_public',
        ),
    ]
