# Generated by Django 3.2 on 2023-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_space_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='privacy',
            field=models.CharField(default='public', max_length=255),
        ),
    ]
