# Generated by Django 3.2 on 2023-05-31 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_space_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='app1.step')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='app1.step')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workflow')),
            ],
        ),
    ]
