# Generated by Django 3.2 on 2023-06-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20230601_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('ticket_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.membership')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.step')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.workflow')),
            ],
        ),
    ]
