# Generated by Django 3.2 on 2023-08-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20230708_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
