# Generated by Django 3.2 on 2023-09-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_step_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workflow'),
        ),
    ]
