# Generated by Django 3.2 on 2023-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent_ticket',
            field=models.IntegerField(null=True),
        ),
    ]
