# Generated by Django 3.2 on 2023-09-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_ticket_parent_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='parent_ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
