# Generated by Django 3.2 on 2023-10-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_ticket_parent_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sprint Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workflow')),
            ],
        ),
    ]
