# Generated by Django 3.2 on 2023-10-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20231005_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
