# Generated by Django 3.2 on 2023-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20231007_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estimationDurationMinutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
